INSERT INTO "cards" ("occasion_id", "category_id", "image_front", "image_inside", "artist", "details")
VALUES (9, 6, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card1front.jpeg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card1inside.jpeg', 'Wanda Maximoff', 'Pictoral scene that stresses solitude and taking time'),
(2, 5, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card2front.jpeg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card2inside.jpeg', 'Monica Rambeau', 'Sweet Fox, but you are wiser'),
(10, 3, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card3front.jpg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card3inside.png', 'Thor Odinson', 'Setting off on an adventure with you on a Viking ship'),
(9, 7, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card4front.jpg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card4inside.png', 'Darcy Lewis', 'Girl on a boat, dreaming'),
(2, 4, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card5front.jpg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card5inside.png', 'Clint Barton', 'Couple on a beach during sunset expressing togetherness'),
(5, 3, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card6front.jpg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card6inside.png', 'Natasha Romanoff', 'Girl stretching for a fight, dedicated and focused'),
(12, 5, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card7front.jpg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card7inside.png', 'Anthony Stark', 'Mother and children'),
(10, 5, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card8front.jpeg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card8inside.png', 'Pepper Potts', 'Elegant women in dresses'),
(10, 10, 'https://freehand-prime.s3.us-east-2.amazonaws.com/card9front.jpg', 'https://freehand-prime.s3.us-east-2.amazonaws.com/card9inside.jpg', 'Carol Danvers', 'Superhero woman wants some quality time');