INSERT INTO "occasions" ("occasion")
VALUES ('Not Specified'),
('Anniversary'),
('Birthday'),
('Christmas'),
('Graduation'),
('Chanukkah'),
('Thanksgiving'),
('Ramadan'),
('Just Because'),
('Valentines Day'),
('Fathers Day'),
('Mothers Day'),
('New Baby'),
('Sympathy');